version: '3.8'
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: oinkvest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - db-data:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/oinkvest
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
    depends_on:
      - db
volumes:
  db-data:
